/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as LabourRouteImport } from './routes/labour'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarblePhotosRouteImport } from './routes/marble.photos'
import { Route as MarbleCategoriesRouteImport } from './routes/marble.categories'
import { Route as InventoryRawRouteImport } from './routes/inventory.raw'
import { Route as InventoryFinishedRouteImport } from './routes/inventory.finished'

const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const LabourRoute = LabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarblePhotosRoute = MarblePhotosRouteImport.update({
  id: '/marble/photos',
  path: '/marble/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarbleCategoriesRoute = MarbleCategoriesRouteImport.update({
  id: '/marble/categories',
  path: '/marble/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRawRoute = InventoryRawRouteImport.update({
  id: '/inventory/raw',
  path: '/inventory/raw',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryFinishedRoute = InventoryFinishedRouteImport.update({
  id: '/inventory/finished',
  path: '/inventory/finished',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/labour': typeof LabourRoute
  '/lending': typeof LendingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/marble/categories': typeof MarbleCategoriesRoute
  '/marble/photos': typeof MarblePhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/labour': typeof LabourRoute
  '/lending': typeof LendingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/marble/categories': typeof MarbleCategoriesRoute
  '/marble/photos': typeof MarblePhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/labour': typeof LabourRoute
  '/lending': typeof LendingRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/sales': typeof SalesRoute
  '/suppliers': typeof SuppliersRoute
  '/inventory/finished': typeof InventoryFinishedRoute
  '/inventory/raw': typeof InventoryRawRoute
  '/marble/categories': typeof MarbleCategoriesRoute
  '/marble/photos': typeof MarblePhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/labour'
    | '/lending'
    | '/login'
    | '/payments'
    | '/sales'
    | '/suppliers'
    | '/inventory/finished'
    | '/inventory/raw'
    | '/marble/categories'
    | '/marble/photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/labour'
    | '/lending'
    | '/login'
    | '/payments'
    | '/sales'
    | '/suppliers'
    | '/inventory/finished'
    | '/inventory/raw'
    | '/marble/categories'
    | '/marble/photos'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/labour'
    | '/lending'
    | '/login'
    | '/payments'
    | '/sales'
    | '/suppliers'
    | '/inventory/finished'
    | '/inventory/raw'
    | '/marble/categories'
    | '/marble/photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  LabourRoute: typeof LabourRoute
  LendingRoute: typeof LendingRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  SalesRoute: typeof SalesRoute
  SuppliersRoute: typeof SuppliersRoute
  InventoryFinishedRoute: typeof InventoryFinishedRoute
  InventoryRawRoute: typeof InventoryRawRoute
  MarbleCategoriesRoute: typeof MarbleCategoriesRoute
  MarblePhotosRoute: typeof MarblePhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labour': {
      id: '/labour'
      path: '/labour'
      fullPath: '/labour'
      preLoaderRoute: typeof LabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marble/photos': {
      id: '/marble/photos'
      path: '/marble/photos'
      fullPath: '/marble/photos'
      preLoaderRoute: typeof MarblePhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marble/categories': {
      id: '/marble/categories'
      path: '/marble/categories'
      fullPath: '/marble/categories'
      preLoaderRoute: typeof MarbleCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/raw': {
      id: '/inventory/raw'
      path: '/inventory/raw'
      fullPath: '/inventory/raw'
      preLoaderRoute: typeof InventoryRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/finished': {
      id: '/inventory/finished'
      path: '/inventory/finished'
      fullPath: '/inventory/finished'
      preLoaderRoute: typeof InventoryFinishedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  LabourRoute: LabourRoute,
  LendingRoute: LendingRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  SalesRoute: SalesRoute,
  SuppliersRoute: SuppliersRoute,
  InventoryFinishedRoute: InventoryFinishedRoute,
  InventoryRawRoute: InventoryRawRoute,
  MarbleCategoriesRoute: MarbleCategoriesRoute,
  MarblePhotosRoute: MarblePhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
