// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxhceemmjhigbacewdjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4aGNlZW1tamhpZ2JhY2V3ZGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NzAyMzAsImV4cCI6MjA5MzM0NjIzMH0.495kexZNhBTBrBcnVrCmlUMffP2-pVFuMEEKdC0_Xoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});
